// Generated by https://quicktype.io

export interface ICreateProductResponse {
    message: string;
    product: Product;
}

interface Product {
    id:              string;
    name:            string;
    category_id:     number;
    description:     string;
    product_type_id: number;
    price:           number;
    code:            string;
    exchange_rate:   string;
    slug:            string;
}
