// Generated by https://quicktype.io

export interface IProductTypesResponse {
    productTypes: IProductType[];
}

export interface IProductType {
    id:         number;
    name:       string;
    created_at: string;
    updated_at: string;
}
